services:
  - type: web
    name: pbkk-ta-checker
    env: php
    buildCommand: bash build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SENOPATI_BASE_URL
        value: https://senopati.its.ac.id/senopati-lokal-dev/generate
      - key: SENOPATI_MODEL
        value: dolphin-mixtral:latest
